// Code generated by @meterforge/typespec-go. DO NOT EDIT.

package meterforge

type CustomersCreditsService struct {
	client       *Client
	Grants       *CustomersCreditsGrantsService
	Balance      *CustomersCreditsBalanceService
	Adjustments  *CustomersCreditsAdjustmentsService
	Transactions *CustomersCreditsTransactionsService
}
