// Code generated by @meterforge/typespec-go. DO NOT EDIT.

package meterforge

import (
	"context"
	"fmt"
	"net/http"
)

type EntitlementsService struct {
	client *Client
}

func (s *EntitlementsService) ListCustomerAccess(ctx context.Context, customerID string) (*ListCustomerEntitlementAccessResponseData, error) {
	if customerID == "" {
		return nil, fmt.Errorf("meterforge: %s must not be empty: %w", "customerID", ErrEmptyID)
	}

	path := "/meterforge/customers/{customerId}/entitlement-access"

	path = replacePathParam(path, "customerId", customerID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodGet, path, nil, nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out ListCustomerEntitlementAccessResponseData
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
