// Code generated by @meterforge/typespec-go. DO NOT EDIT.

package meterforge

import (
	"context"
	"fmt"
	"iter"
	"net/http"
	"net/url"
)

type PlansService struct {
	client *Client
}

type PlanFilter struct {
	Key      *StringFilter
	Name     *StringFilter
	Status   *StringExactFilter
	Currency *StringExactFilter
}

type PlanListParams struct {
	Page   *PageParams
	Sort   *Sort
	Filter *PlanFilter
}

func (p PlanListParams) values() url.Values {
	q := url.Values{}

	addPageParams(q, p.Page)

	addSort(q, "sort", p.Sort)

	if p.Filter != nil {
		addStringFilter(q, "filter[key]", p.Filter.Key)
		addStringFilter(q, "filter[name]", p.Filter.Name)
		addStringExactFilter(q, "filter[status]", p.Filter.Status)
		addStringExactFilter(q, "filter[currency]", p.Filter.Currency)
	}

	return q
}

// List all plans.
func (s *PlansService) List(ctx context.Context, params PlanListParams) (*PlanPagePaginatedResponse, error) {
	path := "/meterforge/plans"

	req, err := s.client.newRequestWithContentType(ctx, http.MethodGet, path, params.values(), nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out PlanPagePaginatedResponse
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// ListAll returns an iterator over all Plan results, fetching pages of List transparently. Iteration stops at the first error, which is yielded as the second value.
func (s *PlansService) ListAll(ctx context.Context, params PlanListParams) iter.Seq2[Plan, error] {
	return paginate(params.Page, func(page, size int) ([]Plan, int, error) {
		pageParams := params
		pageParams.Page = &PageParams{Size: Int(size), Number: Int(page)}

		resp, err := s.List(ctx, pageParams)
		if err != nil {
			return nil, 0, err
		}

		return resp.Data, resp.Meta.Page.Total, nil
	})
}

// Create a new plan.
func (s *PlansService) Create(ctx context.Context, request CreatePlanRequest) (*Plan, error) {
	path := "/meterforge/plans"

	req, err := s.client.newRequestWithContentType(ctx, http.MethodPost, path, nil, request, "application/json", "application/json")
	if err != nil {
		return nil, err
	}

	var out Plan
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Update a plan by id.
func (s *PlansService) Update(ctx context.Context, planID string, request UpsertPlanRequest) (*Plan, error) {
	if planID == "" {
		return nil, fmt.Errorf("meterforge: %s must not be empty: %w", "planID", ErrEmptyID)
	}

	path := "/meterforge/plans/{planId}"

	path = replacePathParam(path, "planId", planID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodPut, path, nil, request, "application/json", "application/json")
	if err != nil {
		return nil, err
	}

	var out Plan
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Get a plan by id.
func (s *PlansService) Get(ctx context.Context, planID string) (*Plan, error) {
	if planID == "" {
		return nil, fmt.Errorf("meterforge: %s must not be empty: %w", "planID", ErrEmptyID)
	}

	path := "/meterforge/plans/{planId}"

	path = replacePathParam(path, "planId", planID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodGet, path, nil, nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out Plan
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Delete a plan by id.
func (s *PlansService) Delete(ctx context.Context, planID string) error {
	if planID == "" {
		return fmt.Errorf("meterforge: %s must not be empty: %w", "planID", ErrEmptyID)
	}

	path := "/meterforge/plans/{planId}"

	path = replacePathParam(path, "planId", planID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodDelete, path, nil, nil, "", "")
	if err != nil {
		return err
	}

	_, err = s.client.doRaw(req)
	return err
}

// Archive a plan version.
func (s *PlansService) Archive(ctx context.Context, planID string) (*Plan, error) {
	if planID == "" {
		return nil, fmt.Errorf("meterforge: %s must not be empty: %w", "planID", ErrEmptyID)
	}

	path := "/meterforge/plans/{planId}/archive"

	path = replacePathParam(path, "planId", planID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodPost, path, nil, nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out Plan
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Publish a plan version.
func (s *PlansService) Publish(ctx context.Context, planID string) (*Plan, error) {
	if planID == "" {
		return nil, fmt.Errorf("meterforge: %s must not be empty: %w", "planID", ErrEmptyID)
	}

	path := "/meterforge/plans/{planId}/publish"

	path = replacePathParam(path, "planId", planID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodPost, path, nil, nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out Plan
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
