blank_issues_enabled: true
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/Pototoooo/meterforge/discussions/new?category=q-a
    about: Ask and discuss questions with other MeterForge community members

  - name: 💬 Discord
    url: https://discord.gg/nYH3ZQ3Xzq
    about: Please ask and answer questions here
