// Code generated by @meterforge/typespec-typescript. DO NOT EDIT.

import { type Client } from '../core.js'
import { unwrap, type RequestOptions } from '../lib/types.js'
import { paginatePages } from '../lib/paginate.js'
import {
  createTaxCode,
  getTaxCode,
  listTaxCodes,
  upsertTaxCode,
  deleteTaxCode,
} from '../funcs/tax.js'
import type {
  CreateTaxCodeRequest,
  CreateTaxCodeResponse,
  GetTaxCodeRequest,
  GetTaxCodeResponse,
  ListTaxCodesRequest,
  ListTaxCodesResponse,
  UpsertTaxCodeRequest,
  UpsertTaxCodeResponse,
  DeleteTaxCodeRequest,
  DeleteTaxCodeResponse,
} from '../models/operations/tax.js'
import type { TaxCode } from '../models/types.js'

export class Tax {
  constructor(private readonly _client: Client) {}

  /**
   * Create tax code
   *
   * POST /meterforge/tax-codes
   */
  async createCode(
    request: CreateTaxCodeRequest,
    options?: RequestOptions,
  ): Promise<CreateTaxCodeResponse> {
    return unwrap(await createTaxCode(this._client, request, options))
  }

  /**
   * Get tax code
   *
   * GET /meterforge/tax-codes/{taxCodeId}
   */
  async getCode(
    request: GetTaxCodeRequest,
    options?: RequestOptions,
  ): Promise<GetTaxCodeResponse> {
    return unwrap(await getTaxCode(this._client, request, options))
  }

  /**
   * List tax codes
   *
   * GET /meterforge/tax-codes
   */
  async listCodes(
    request?: ListTaxCodesRequest,
    options?: RequestOptions,
  ): Promise<ListTaxCodesResponse> {
    return unwrap(await listTaxCodes(this._client, request, options))
  }

  /**
   * List tax codes
   *
   * Iterates every item across all pages, fetching more as the returned iterable is consumed.
   *
   * GET /meterforge/tax-codes
   */
  listCodesAll(
    request?: ListTaxCodesRequest,
    options?: RequestOptions,
  ): AsyncIterable<TaxCode> {
    return paginatePages(
      (req, opts) => listTaxCodes(this._client, req, opts),
      request ?? {},
      options,
    )
  }

  /**
   * Upsert tax code
   *
   * PUT /meterforge/tax-codes/{taxCodeId}
   */
  async upsertCode(
    request: UpsertTaxCodeRequest,
    options?: RequestOptions,
  ): Promise<UpsertTaxCodeResponse> {
    return unwrap(await upsertTaxCode(this._client, request, options))
  }

  /**
   * Delete tax code
   *
   * DELETE /meterforge/tax-codes/{taxCodeId}
   */
  async deleteCode(
    request: DeleteTaxCodeRequest,
    options?: RequestOptions,
  ): Promise<DeleteTaxCodeResponse> {
    return unwrap(await deleteTaxCode(this._client, request, options))
  }
}
