// Code generated by @meterforge/typespec-typescript. DO NOT EDIT.

import type { ListCustomerEntitlementAccessResponseData } from '../types.js'

export type ListCustomerEntitlementAccessRequest = {
  customerId: string
}
export type ListCustomerEntitlementAccessResponse =
  ListCustomerEntitlementAccessResponseData
